'use client'

import { useRef, useState } from 'react'
import { X, Download, Upload, Trash2, Info, User, Type, Heart, Share2, Copy, FileImage, ChevronRight } from 'lucide-react'
import { useNasabStore } from '@/lib/store'
import { ConfirmDialog } from './confirm-dialog'
import { getRelationToSelf } from '@/lib/relationship'
import type { FontSize } from '@/lib/types'

interface MenuDrawerProps {
  open: boolean
  onClose: () => void
  onViewSelf: () => void
  showToast: (message: string) => void
}

export function MenuDrawer({ open, onClose, onViewSelf, showToast }: MenuDrawerProps) {
  const [showImport, setShowImport] = useState(false)
  const [importText, setImportText] = useState('')
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  const [showShare, setShowShare] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)
  
  const { members, settings, exportData, importData, clearAllData, setFontSize, getParents, getChildren, getSpouses } = useNasabStore()
  const self = members.find(m => m.isSelf)
  const fontSize = settings.fontSize || 'medium'

  // Generate silsilah text (genealogy lineage from self to ancestors)
  const generateSilsilahText = () => {
    if (!self) return ''

    const lines: string[] = []
    lines.push('SILSILAH KELUARGA')
    lines.push('Generated by NasabQ')
    lines.push('=' .repeat(40))
    lines.push('')

    // Add self info
    lines.push(`NAMA: ${self.name}`)
    if (self.nickname) lines.push(`Panggilan: ${self.nickname}`)
    if (self.birthYear) lines.push(`Tahun Lahir: ${self.birthYear}`)
    if (self.address) lines.push(`Domisili: ${self.address}`)
    lines.push('')

    // Get ancestors path
    const getAncestorPath = (id: number, visited = new Set<number>()): string[] => {
      if (visited.has(id)) return []
      visited.add(id)
      const parents = getParents(id)
      if (parents.length === 0) return []
      
      const paths: string[] = []
      for (const parent of parents) {
        const relation = parent.gender === 'M' ? 'Ayah' : 'Ibu'
        paths.push(`${relation}: ${parent.name}${parent.birthYear ? ` (${parent.birthYear})` : ''}`)
        const ancestorPaths = getAncestorPath(parent.id, new Set(visited))
        paths.push(...ancestorPaths.map(p => '  ' + p))
      }
      return paths
    }

    lines.push('GARIS KETURUNAN:')
    lines.push('-'.repeat(40))
    const ancestorPaths = getAncestorPath(self.id)
    if (ancestorPaths.length > 0) {
      lines.push(...ancestorPaths)
    } else {
      lines.push('(Belum ada data orang tua)')
    }
    lines.push('')

    // Add all family members summary
    lines.push('DAFTAR ANGGOTA KELUARGA:')
    lines.push('-'.repeat(40))
    members.forEach(member => {
      const relation = member.isSelf ? 'Kamu' : getRelationToSelf(member.id, self.id, members, getParents, getChildren, getSpouses) || '-'
      const status = member.isDeceased ? ' (Almarhum/ah)' : ''
      lines.push(`- ${member.name}${status} [${relation}]`)
    })

    lines.push('')
    lines.push('=' .repeat(40))
    lines.push(`Total: ${members.length} anggota keluarga`)

    return lines.join('\n')
  }

  // Copy silsilah text to clipboard
  const handleCopySilsilah = async () => {
    const text = generateSilsilahText()
    try {
      await navigator.clipboard.writeText(text)
      showToast('Silsilah berhasil disalin!')
    } catch {
      showToast('Gagal menyalin silsilah')
    }
  }

  // Save tree as image - generate SVG-based image
  const handleSaveAsImage = () => {
    if (!self) {
      showToast('Tidak ada data untuk disimpan')
      return
    }

    // Generate a simple family tree representation as downloadable text/image
    const generateTreeSVG = () => {
      const width = 800
      const nodeHeight = 60
      const nodeWidth = 150
      const verticalGap = 40
      
      // Build hierarchy
      const buildHierarchy = (memberId: number, level: number = 0, visited = new Set<number>()): { member: typeof members[0], level: number, children: ReturnType<typeof buildHierarchy>[] } | null => {
        if (visited.has(memberId)) return null
        visited.add(memberId)
        
        const member = members.find(m => m.id === memberId)
        if (!member) return null
        
        const children = getChildren(memberId)
          .map(child => buildHierarchy(child.id, level + 1, new Set(visited)))
          .filter((c): c is NonNullable<typeof c> => c !== null)
        
        return { member, level, children }
      }

      // Find root (oldest generation)
      const roots = members.filter(m => getParents(m.id).length === 0)
      
      // Generate SVG content
      let svgContent = ''
      let y = 40
      const processedIds = new Set<number>()

      const drawMember = (member: typeof members[0], x: number, currentY: number, indent: number = 0) => {
        if (processedIds.has(member.id)) return currentY
        processedIds.add(member.id)
        
        const bgColor = member.isSelf ? '#10b981' : member.gender === 'M' ? '#0d6a51' : '#db4f8a'
        const textColor = '#ffffff'
        const name = member.nickname || member.name.split(' ')[0]
        const label = member.isSelf ? ' (Kamu)' : ''
        const deceased = member.isDeceased ? ' *' : ''
        
        svgContent += `
          <rect x="${x + indent * 20}" y="${currentY}" width="${nodeWidth}" height="${nodeHeight - 10}" rx="8" fill="${bgColor}" />
          <text x="${x + indent * 20 + nodeWidth/2}" y="${currentY + 25}" text-anchor="middle" fill="${textColor}" font-family="system-ui, sans-serif" font-size="12" font-weight="600">${name}${label}${deceased}</text>
          ${member.birthYear ? `<text x="${x + indent * 20 + nodeWidth/2}" y="${currentY + 42}" text-anchor="middle" fill="${textColor}" font-family="system-ui, sans-serif" font-size="10" opacity="0.8">${member.birthYear}</text>` : ''}
        `
        
        return currentY + nodeHeight + verticalGap / 2
      }

      // Sort members by generation
      const getGen = (id: number, visited = new Set<number>()): number => {
        if (visited.has(id)) return 0
        visited.add(id)
        const parents = getParents(id)
        if (parents.length === 0) return 0
        return 1 + Math.max(...parents.map(p => getGen(p.id, new Set(visited))))
      }

      const sortedMembers = [...members].sort((a, b) => {
        const genDiff = getGen(a.id) - getGen(b.id)
        if (genDiff !== 0) return genDiff
        if (a.isSelf) return -1
        if (b.isSelf) return 1
        return a.name.localeCompare(b.name)
      })

      // Group by generation
      const generations = new Map<number, typeof members>()
      sortedMembers.forEach(m => {
        const gen = getGen(m.id)
        if (!generations.has(gen)) generations.set(gen, [])
        generations.get(gen)!.push(m)
      })

      // Draw by generation
      let currentY = 60
      const sortedGens = [...generations.entries()].sort((a, b) => a[0] - b[0])
      
      sortedGens.forEach(([gen, genMembers]) => {
        // Generation label
        svgContent += `<text x="20" y="${currentY}" font-family="system-ui, sans-serif" font-size="11" fill="#666" font-weight="500">Generasi ${gen}</text>`
        currentY += 20
        
        // Draw members in this generation
        let x = 20
        genMembers.forEach((member, idx) => {
          if (x + nodeWidth > width - 20) {
            x = 20
            currentY += nodeHeight + 10
          }
          
          const bgColor = member.isSelf ? '#10b981' : member.gender === 'M' ? '#0d6a51' : '#db4f8a'
          const name = (member.nickname || member.name.split(' ')[0]).substring(0, 12)
          const label = member.isSelf ? '*' : ''
          const deceased = member.isDeceased ? ' (Alm)' : ''
          
          svgContent += `
            <rect x="${x}" y="${currentY}" width="${nodeWidth}" height="${nodeHeight - 10}" rx="8" fill="${bgColor}" />
            <text x="${x + nodeWidth/2}" y="${currentY + 22}" text-anchor="middle" fill="#fff" font-family="system-ui, sans-serif" font-size="11" font-weight="600">${name}${label}</text>
            <text x="${x + nodeWidth/2}" y="${currentY + 38}" text-anchor="middle" fill="#fff" font-family="system-ui, sans-serif" font-size="9" opacity="0.8">${member.birthYear || ''}${deceased}</text>
          `
          x += nodeWidth + 15
        })
        currentY += nodeHeight + 25
      })

      const totalHeight = currentY + 60

      return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${totalHeight}" viewBox="0 0 ${width} ${totalHeight}">
  <rect width="100%" height="100%" fill="#f5f5f0"/>
  <text x="${width/2}" y="30" text-anchor="middle" font-family="system-ui, sans-serif" font-size="18" font-weight="bold" fill="#0d6a51">Silsilah Keluarga - NasabQ</text>
  ${svgContent}
  <text x="${width/2}" y="${totalHeight - 15}" text-anchor="middle" font-family="system-ui, sans-serif" font-size="10" fill="#999">* = Kamu | Total: ${members.length} anggota | Generated by NasabQ</text>
</svg>`
    }

    try {
      const svg = generateTreeSVG()
      const blob = new Blob([svg], { type: 'image/svg+xml' })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `nasabq-silsilah-${new Date().toISOString().split('T')[0]}.svg`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
      showToast('Gambar silsilah berhasil disimpan!')
      onClose()
    } catch {
      showToast('Gagal menyimpan gambar')
    }
  }

  const fontSizeOptions: { value: FontSize; label: string }[] = [
    { value: 'small', label: 'Kecil' },
    { value: 'medium', label: 'Sedang' },
    { value: 'large', label: 'Besar' },
  ]

  const handleExport = () => {
    const data = exportData()
    const json = JSON.stringify(data, null, 2)
    const blob = new Blob([json], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `nasab-${new Date().toISOString().split('T')[0]}.json`
    a.click()
    URL.revokeObjectURL(url)
    showToast('Data berhasil diunduh!')
  }

  const handleImportFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    
    const reader = new FileReader()
    reader.onload = (event) => {
      try {
        const data = JSON.parse(event.target?.result as string)
        if (data.members && Array.isArray(data.members) && typeof data.nextId === 'number') {
          // Ensure settings exists
          if (!data.settings) {
            data.settings = { darkMode: false }
          }
          importData(data)
          showToast('Data berhasil diimpor!')
          setShowImport(false)
          onClose()
        } else {
          showToast('Format file tidak valid')
        }
      } catch {
        showToast('Gagal membaca file')
      }
    }
    reader.readAsText(file)
    // Reset file input
    e.target.value = ''
  }

  const handleImportText = () => {
    try {
      const data = JSON.parse(importText)
      if (data.members && Array.isArray(data.members) && typeof data.nextId === 'number') {
        // Ensure settings exists
        if (!data.settings) {
          data.settings = { darkMode: false }
        }
        importData(data)
        showToast('Data berhasil diimpor!')
        setShowImport(false)
        setImportText('')
        onClose()
      } else {
        showToast('Format data tidak valid')
      }
    } catch {
      showToast('Format JSON tidak valid')
    }
  }

  const handleClearAll = () => {
    setShowDeleteConfirm(true)
  }

  const confirmClearAll = () => {
    clearAllData()
    showToast('Semua data dihapus')
    setShowDeleteConfirm(false)
    onClose()
  }

  if (!open) return null

  return (
    <>
    <div className="fixed inset-0 z-50">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-foreground/40 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Drawer */}
      <div className="absolute right-0 top-0 bottom-0 w-[280px] md:w-[320px] bg-card drawer-slide overflow-y-auto">
        {/* Header */}
        <div className="sticky top-0 bg-card z-10 p-4 border-b border-border flex items-center justify-between">
          <h2 className="font-display font-bold text-lg">Menu</h2>
          <button
            onClick={onClose}
            className="w-8 h-8 flex items-center justify-center rounded-full hover:bg-muted transition-colors"
            aria-label="Tutup"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-4 space-y-6">
          {/* Profile Section */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Profil</h3>
            {self && (
              <button
                onClick={onViewSelf}
                className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-muted/80 active:scale-[0.98] transition-all"
              >
                <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                  <User className="w-5 h-5 text-primary" />
                </div>
                <div className="flex-1 text-left">
                  <p className="font-display font-semibold text-sm">{self.name}</p>
                  <span className="inline-block px-1.5 py-0.5 text-[10px] font-semibold bg-gold/20 text-gold rounded mt-0.5">
                    Kamu
                  </span>
                </div>
              </button>
            )}
          </section>

          {/* Appearance Section */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Tampilan</h3>
            {/* Font Size */}
            <div className="p-3 bg-muted rounded-lg">
              <div className="flex items-center gap-3 mb-3">
                <Type className="w-5 h-5" />
                <span className="text-sm font-medium">Ukuran Font</span>
              </div>
              <div className="flex gap-2">
                {fontSizeOptions.map((option) => (
                  <button
                    key={option.value}
                    onClick={() => setFontSize(option.value)}
                    className={`flex-1 py-2 px-3 text-xs font-medium rounded-lg transition-colors ${
                      fontSize === option.value
                        ? 'bg-primary text-primary-foreground'
                        : 'bg-card border border-border hover:border-primary'
                    }`}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            </div>
          </section>

          {/* Share Section */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Bagikan</h3>
            <div className="space-y-2">
              <div>
                <button
                  onClick={() => setShowShare(!showShare)}
                  className="w-full p-3 bg-primary/10 rounded-lg flex items-center gap-3 hover:bg-primary/20 transition-colors"
                >
                  <Share2 className="w-5 h-5 text-primary" />
                  <span className="text-sm font-medium text-primary flex-1 text-left">Bagikan Silsilah</span>
                  <ChevronRight className={`w-4 h-4 text-primary transition-transform ${showShare ? 'rotate-90' : ''}`} />
                </button>

                {showShare && (
                  <div className="mt-2 space-y-2">
                    {/* Copy Silsilah Text */}
                    <button
                      onClick={handleCopySilsilah}
                      className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-muted/80 active:scale-[0.98] transition-all"
                    >
                      <Copy className="w-4 h-4" />
                      <div className="flex-1 text-left">
                        <span className="text-sm font-medium block">Salin Teks Silsilah</span>
                        <span className="text-[10px] text-muted-foreground">Format teks untuk dibagikan</span>
                      </div>
                    </button>

                    {/* Save as Image */}
                    <button
                      onClick={handleSaveAsImage}
                      className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-muted/80 active:scale-[0.98] transition-all"
                    >
                      <FileImage className="w-4 h-4" />
                      <div className="flex-1 text-left">
                        <span className="text-sm font-medium block">Simpan Gambar Pohon</span>
                        <span className="text-[10px] text-muted-foreground">Export sebagai gambar SVG</span>
                      </div>
                    </button>
                  </div>
                )}
              </div>
            </div>
          </section>

          {/* Data Section */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Data</h3>
            <div className="space-y-2">
              <button
                onClick={handleExport}
                className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-muted/80 active:scale-[0.98] transition-all"
              >
                <Download className="w-5 h-5" />
                <span className="text-sm font-medium">Export Data (JSON)</span>
              </button>

              <div>
                <button
                  onClick={() => setShowImport(!showImport)}
                  className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-muted/80 transition-colors"
                >
                  <Upload className="w-5 h-5" />
                  <span className="text-sm font-medium">Import Data</span>
                </button>
                
                {showImport && (
                  <div className="mt-2 p-3 bg-muted/50 rounded-lg space-y-3">
                    <input
                      ref={fileInputRef}
                      type="file"
                      accept=".json"
                      onChange={handleImportFile}
                      className="hidden"
                    />
                    <button
                      onClick={() => fileInputRef.current?.click()}
                      className="w-full p-2 text-xs font-medium border border-dashed border-border rounded-lg hover:border-primary hover:text-primary transition-colors"
                    >
                      Pilih File JSON
                    </button>
                    <div className="relative">
                      <textarea
                        value={importText}
                        onChange={(e) => setImportText(e.target.value)}
                        placeholder="Atau tempel JSON di sini..."
                        className="w-full h-20 p-2 text-xs bg-card border border-border rounded-lg resize-none focus:outline-none focus:ring-1 focus:ring-primary"
                      />
                    </div>
                    {importText && (
                      <button
                        onClick={handleImportText}
                        className="w-full p-2 text-xs font-semibold bg-primary text-primary-foreground rounded-lg hover:bg-primary-hover transition-colors"
                      >
                        Import
                      </button>
                    )}
                  </div>
                )}
              </div>

              <button
                onClick={handleClearAll}
                className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-destructive/10 text-destructive transition-colors"
              >
                <Trash2 className="w-5 h-5" />
                <span className="text-sm font-medium">Hapus Semua Data</span>
              </button>
            </div>
          </section>

          {/* Info Section */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Info</h3>
            <div className="p-3 bg-muted rounded-lg flex items-start gap-3">
              <Info className="w-5 h-5 text-muted-foreground flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-semibold">Tentang NasabQ</p>
                <p className="text-xs text-muted-foreground mt-1">
                  Aplikasi silsilah keluarga untuk menyimpan dan mengenal akar keluargamu.
                </p>
                <p className="text-xs text-muted-foreground mt-2 flex items-center gap-1">
                  Built with{' '}
                  <Heart className="w-3 h-3 text-red-500 fill-red-500" />
                  {' '}by{' '}
                  <a 
                    href="https://alfindigital.com" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="text-primary hover:underline font-medium"
                  >
                    @alfindigital
                  </a>
                </p>
                <p className="text-[10px] text-muted-foreground/60 mt-2">v1.0.0</p>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>

    <ConfirmDialog
      open={showDeleteConfirm}
      title="Hapus Semua Data"
      message="Semua data silsilah keluarga akan dihapus. Tindakan ini tidak dapat dibatalkan."
      confirmLabel="Hapus"
      cancelLabel="Batal"
      variant="danger"
      onConfirm={confirmClearAll}
      onCancel={() => setShowDeleteConfirm(false)}
    />
    </>
  )
}
