'use client'

import { useRef, useState } from 'react'
import { X, Download, Upload, Trash2, Info, User, Type, Heart, Share2, Copy, FileImage, Link2, ChevronRight } from 'lucide-react'
import { useNasabStore } from '@/lib/store'
import { ConfirmDialog } from './confirm-dialog'
import { getRelationToSelf } from '@/lib/relationship'
import type { FontSize } from '@/lib/types'

interface MenuDrawerProps {
  open: boolean
  onClose: () => void
  onViewSelf: () => void
  showToast: (message: string) => void
}

export function MenuDrawer({ open, onClose, onViewSelf, showToast }: MenuDrawerProps) {
  const [showImport, setShowImport] = useState(false)
  const [importText, setImportText] = useState('')
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  const [showShare, setShowShare] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)
  
  const { members, settings, exportData, importData, clearAllData, setFontSize, getParents, getChildren, getSpouses } = useNasabStore()
  const self = members.find(m => m.isSelf)
  const fontSize = settings.fontSize || 'medium'

  // Generate silsilah text (genealogy lineage from self to ancestors)
  const generateSilsilahText = () => {
    if (!self) return ''

    const lines: string[] = []
    lines.push('SILSILAH KELUARGA')
    lines.push('Generated by NasabQ')
    lines.push('=' .repeat(40))
    lines.push('')

    // Add self info
    lines.push(`NAMA: ${self.name}`)
    if (self.nickname) lines.push(`Panggilan: ${self.nickname}`)
    if (self.birthYear) lines.push(`Tahun Lahir: ${self.birthYear}`)
    if (self.address) lines.push(`Domisili: ${self.address}`)
    lines.push('')

    // Get ancestors path
    const getAncestorPath = (id: number, visited = new Set<number>()): string[] => {
      if (visited.has(id)) return []
      visited.add(id)
      const parents = getParents(id)
      if (parents.length === 0) return []
      
      const paths: string[] = []
      for (const parent of parents) {
        const relation = parent.gender === 'M' ? 'Ayah' : 'Ibu'
        paths.push(`${relation}: ${parent.name}${parent.birthYear ? ` (${parent.birthYear})` : ''}`)
        const ancestorPaths = getAncestorPath(parent.id, new Set(visited))
        paths.push(...ancestorPaths.map(p => '  ' + p))
      }
      return paths
    }

    lines.push('GARIS KETURUNAN:')
    lines.push('-'.repeat(40))
    const ancestorPaths = getAncestorPath(self.id)
    if (ancestorPaths.length > 0) {
      lines.push(...ancestorPaths)
    } else {
      lines.push('(Belum ada data orang tua)')
    }
    lines.push('')

    // Add all family members summary
    lines.push('DAFTAR ANGGOTA KELUARGA:')
    lines.push('-'.repeat(40))
    members.forEach(member => {
      const relation = member.isSelf ? 'Kamu' : getRelationToSelf(member.id, self.id, members, getParents, getChildren, getSpouses) || '-'
      const status = member.isDeceased ? ' (Almarhum/ah)' : ''
      lines.push(`- ${member.name}${status} [${relation}]`)
    })

    lines.push('')
    lines.push('=' .repeat(40))
    lines.push(`Total: ${members.length} anggota keluarga`)

    return lines.join('\n')
  }

  // Copy silsilah text to clipboard
  const handleCopySilsilah = async () => {
    const text = generateSilsilahText()
    try {
      await navigator.clipboard.writeText(text)
      showToast('Silsilah berhasil disalin!')
    } catch {
      showToast('Gagal menyalin silsilah')
    }
  }

  // Copy share data (JSON) to clipboard
  const handleCopyShareData = async () => {
    const data = exportData()
    const json = JSON.stringify(data)
    // Encode to base64 for cleaner sharing
    const encoded = btoa(unescape(encodeURIComponent(json)))
    try {
      await navigator.clipboard.writeText(encoded)
      showToast('Data silsilah berhasil disalin! Bagikan ke keluarga untuk diimpor.')
    } catch {
      showToast('Gagal menyalin data')
    }
  }

  // Save tree as image
  const handleSaveAsImage = async () => {
    const treeElement = document.querySelector('[data-tree-canvas]')
    if (!treeElement) {
      showToast('Tree tidak ditemukan')
      return
    }

    try {
      // Dynamically import html2canvas
      const html2canvas = (await import('html2canvas')).default
      const canvas = await html2canvas(treeElement as HTMLElement, {
        backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--background').trim() || '#ffffff',
        scale: 2,
        useCORS: true,
        logging: false,
      })
      
      const link = document.createElement('a')
      link.download = `nasabq-tree-${new Date().toISOString().split('T')[0]}.png`
      link.href = canvas.toDataURL('image/png')
      link.click()
      showToast('Gambar pohon keluarga berhasil disimpan!')
    } catch {
      showToast('Gagal menyimpan gambar')
    }
  }

  const fontSizeOptions: { value: FontSize; label: string }[] = [
    { value: 'small', label: 'Kecil' },
    { value: 'medium', label: 'Sedang' },
    { value: 'large', label: 'Besar' },
  ]

  const handleExport = () => {
    const data = exportData()
    const json = JSON.stringify(data, null, 2)
    const blob = new Blob([json], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `nasab-${new Date().toISOString().split('T')[0]}.json`
    a.click()
    URL.revokeObjectURL(url)
    showToast('Data berhasil diunduh!')
  }

  const handleImportFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    
    const reader = new FileReader()
    reader.onload = (event) => {
      try {
        const data = JSON.parse(event.target?.result as string)
        if (data.members && Array.isArray(data.members) && typeof data.nextId === 'number') {
          // Ensure settings exists
          if (!data.settings) {
            data.settings = { darkMode: false }
          }
          importData(data)
          showToast('Data berhasil diimpor!')
          setShowImport(false)
          onClose()
        } else {
          showToast('Format file tidak valid')
        }
      } catch {
        showToast('Gagal membaca file')
      }
    }
    reader.readAsText(file)
    // Reset file input
    e.target.value = ''
  }

  const handleImportText = () => {
    try {
      const data = JSON.parse(importText)
      if (data.members && Array.isArray(data.members) && typeof data.nextId === 'number') {
        // Ensure settings exists
        if (!data.settings) {
          data.settings = { darkMode: false }
        }
        importData(data)
        showToast('Data berhasil diimpor!')
        setShowImport(false)
        setImportText('')
        onClose()
      } else {
        showToast('Format data tidak valid')
      }
    } catch {
      showToast('Format JSON tidak valid')
    }
  }

  const handleClearAll = () => {
    setShowDeleteConfirm(true)
  }

  const confirmClearAll = () => {
    clearAllData()
    showToast('Semua data dihapus')
    setShowDeleteConfirm(false)
    onClose()
  }

  if (!open) return null

  return (
    <>
    <div className="fixed inset-0 z-50">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-foreground/40 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Drawer */}
      <div className="absolute right-0 top-0 bottom-0 w-[280px] md:w-[320px] bg-card drawer-slide overflow-y-auto">
        {/* Header */}
        <div className="sticky top-0 bg-card z-10 p-4 border-b border-border flex items-center justify-between">
          <h2 className="font-display font-bold text-lg">Menu</h2>
          <button
            onClick={onClose}
            className="w-8 h-8 flex items-center justify-center rounded-full hover:bg-muted transition-colors"
            aria-label="Tutup"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-4 space-y-6">
          {/* Profile Section */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Profil</h3>
            {self && (
              <button
                onClick={onViewSelf}
                className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-muted/80 active:scale-[0.98] transition-all"
              >
                <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                  <User className="w-5 h-5 text-primary" />
                </div>
                <div className="flex-1 text-left">
                  <p className="font-display font-semibold text-sm">{self.name}</p>
                  <span className="inline-block px-1.5 py-0.5 text-[10px] font-semibold bg-gold/20 text-gold rounded mt-0.5">
                    Kamu
                  </span>
                </div>
              </button>
            )}
          </section>

          {/* Appearance Section */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Tampilan</h3>
            {/* Font Size */}
            <div className="p-3 bg-muted rounded-lg">
              <div className="flex items-center gap-3 mb-3">
                <Type className="w-5 h-5" />
                <span className="text-sm font-medium">Ukuran Font</span>
              </div>
              <div className="flex gap-2">
                {fontSizeOptions.map((option) => (
                  <button
                    key={option.value}
                    onClick={() => setFontSize(option.value)}
                    className={`flex-1 py-2 px-3 text-xs font-medium rounded-lg transition-colors ${
                      fontSize === option.value
                        ? 'bg-primary text-primary-foreground'
                        : 'bg-card border border-border hover:border-primary'
                    }`}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            </div>
          </section>

          {/* Share Section */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Bagikan</h3>
            <div className="space-y-2">
              <div>
                <button
                  onClick={() => setShowShare(!showShare)}
                  className="w-full p-3 bg-primary/10 rounded-lg flex items-center gap-3 hover:bg-primary/20 transition-colors"
                >
                  <Share2 className="w-5 h-5 text-primary" />
                  <span className="text-sm font-medium text-primary flex-1 text-left">Bagikan Silsilah</span>
                  <ChevronRight className={`w-4 h-4 text-primary transition-transform ${showShare ? 'rotate-90' : ''}`} />
                </button>

                {showShare && (
                  <div className="mt-2 space-y-2">
                    {/* Copy Silsilah Text */}
                    <button
                      onClick={handleCopySilsilah}
                      className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-muted/80 active:scale-[0.98] transition-all"
                    >
                      <Copy className="w-4 h-4" />
                      <div className="flex-1 text-left">
                        <span className="text-sm font-medium block">Salin Teks Silsilah</span>
                        <span className="text-[10px] text-muted-foreground">Format teks untuk dibagikan</span>
                      </div>
                    </button>

                    {/* Copy Share Data */}
                    <button
                      onClick={handleCopyShareData}
                      className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-muted/80 active:scale-[0.98] transition-all"
                    >
                      <Link2 className="w-4 h-4" />
                      <div className="flex-1 text-left">
                        <span className="text-sm font-medium block">Salin Data Silsilah</span>
                        <span className="text-[10px] text-muted-foreground">Bagikan ke keluarga untuk diimpor</span>
                      </div>
                    </button>

                    {/* Save as Image */}
                    <button
                      onClick={handleSaveAsImage}
                      className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-muted/80 active:scale-[0.98] transition-all"
                    >
                      <FileImage className="w-4 h-4" />
                      <div className="flex-1 text-left">
                        <span className="text-sm font-medium block">Simpan Gambar Pohon</span>
                        <span className="text-[10px] text-muted-foreground">Export pohon keluarga sebagai PNG</span>
                      </div>
                    </button>
                  </div>
                )}
              </div>
            </div>
          </section>

          {/* Data Section */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Data</h3>
            <div className="space-y-2">
              <button
                onClick={handleExport}
                className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-muted/80 active:scale-[0.98] transition-all"
              >
                <Download className="w-5 h-5" />
                <span className="text-sm font-medium">Export Data (JSON)</span>
              </button>

              <div>
                <button
                  onClick={() => setShowImport(!showImport)}
                  className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-muted/80 transition-colors"
                >
                  <Upload className="w-5 h-5" />
                  <span className="text-sm font-medium">Import Data</span>
                </button>
                
                {showImport && (
                  <div className="mt-2 p-3 bg-muted/50 rounded-lg space-y-3">
                    <input
                      ref={fileInputRef}
                      type="file"
                      accept=".json"
                      onChange={handleImportFile}
                      className="hidden"
                    />
                    <button
                      onClick={() => fileInputRef.current?.click()}
                      className="w-full p-2 text-xs font-medium border border-dashed border-border rounded-lg hover:border-primary hover:text-primary transition-colors"
                    >
                      Pilih File JSON
                    </button>
                    <div className="relative">
                      <textarea
                        value={importText}
                        onChange={(e) => setImportText(e.target.value)}
                        placeholder="Atau tempel JSON di sini..."
                        className="w-full h-20 p-2 text-xs bg-card border border-border rounded-lg resize-none focus:outline-none focus:ring-1 focus:ring-primary"
                      />
                    </div>
                    {importText && (
                      <button
                        onClick={handleImportText}
                        className="w-full p-2 text-xs font-semibold bg-primary text-primary-foreground rounded-lg hover:bg-primary-hover transition-colors"
                      >
                        Import
                      </button>
                    )}
                  </div>
                )}
              </div>

              <button
                onClick={handleClearAll}
                className="w-full p-3 bg-muted rounded-lg flex items-center gap-3 hover:bg-destructive/10 text-destructive transition-colors"
              >
                <Trash2 className="w-5 h-5" />
                <span className="text-sm font-medium">Hapus Semua Data</span>
              </button>
            </div>
          </section>

          {/* Info Section */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Info</h3>
            <div className="p-3 bg-muted rounded-lg flex items-start gap-3">
              <Info className="w-5 h-5 text-muted-foreground flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-semibold">Tentang NasabQ</p>
                <p className="text-xs text-muted-foreground mt-1">
                  Aplikasi silsilah keluarga untuk menyimpan dan mengenal akar keluargamu.
                </p>
                <p className="text-xs text-muted-foreground mt-2 flex items-center gap-1">
                  Built with{' '}
                  <Heart className="w-3 h-3 text-red-500 fill-red-500" />
                  {' '}by{' '}
                  <a 
                    href="https://alfindigital.com" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="text-primary hover:underline font-medium"
                  >
                    @alfindigital
                  </a>
                </p>
                <p className="text-[10px] text-muted-foreground/60 mt-2">v1.0.0</p>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>

    <ConfirmDialog
      open={showDeleteConfirm}
      title="Hapus Semua Data"
      message="Semua data silsilah keluarga akan dihapus. Tindakan ini tidak dapat dibatalkan."
      confirmLabel="Hapus"
      cancelLabel="Batal"
      variant="danger"
      onConfirm={confirmClearAll}
      onCancel={() => setShowDeleteConfirm(false)}
    />
    </>
  )
}
